# Default values for socrates.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

adminPassword: 1234
adminEmail: admin@socrates.com

authSecret: random_string

client:
  replicaCount: 1
  image:
    repository: jatalocks333/socrates-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

server:
  replicaCount: 1
  database:
    user: user
    password: password
  image:
    repository: jatalocks333/socrates-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 4000
    annotations: {}
  minio:
    externalAddress: socrates.minio.my.domain
  annotations: {}    
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

worker:
  replicaCount: 1
  storage: 3Gi
  # storageClass: gp2
  image:
    repository: jatasocrates/socrates-server
    tag: v1
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 2375
    annotations: {}
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - socrates.my.domain
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  minio:
    enabled: false
    hosts:  
      - socrates.minio.my.domain  

mongodb:
  persistence:
    enabled: true
  architecture: replicaset
  replicaCount: 3
  auth:
    enabled: true
    usernames: 
      - user
    passwords: 
      - password
    databases: 
      - meandatabase

minio:
  persistence:
    enabled: true
  mode: distributed
  auth:
    rootUser: AKIAIOSFODNN7EXAMPLE
    rootPassword: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY