version: '3.7'
services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: on-failure
    command: server /data --console-address ":9001"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE  
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000
      - 9001:9001
  mongodb:
    image : davybello/mongo-replica-set:4.4.8
    container_name: mongodb
    restart: on-failure
    volumes:
      - "./.data/mongo1:/var/lib/mongo1"
      - "./.data/mongo2:/var/lib/mongo2"
      - "./.data/mongo3:/var/lib/mongo3"
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    entrypoint: dockerd -H tcp://0.0.0.0:2375
    volumes:
      - /tmp:/tmp
    expose:
      - 2375
  server:
    build: backend
    container_name: server
    restart: always
    image: jatalocks333/socrates-backend:latest
    ports:
      - '4000:4000'
    volumes:
      - /tmp:/tmp
    environment:
      - DB_NAME=mongodb
      - DOCKER_TLS_CERTDIR=
      - DOCKER_HOST=tcp://docker:2375      
      - MINIO_ADDR=minio
    links:
      - mongodb
      - docker
  client:
    container_name: client
    build: .
    image: jatalocks333/socrates-frontend:latest
    restart: always
    ports:
      - '80:80'
    environment:
      - SERVER_ADDRESS=server
    command: ["/bin/sh","-c","envsubst '$${SERVER_ADDRESS}'< /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]

# volumes:
#   mongodb4_data: