apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "socrates.fullname" . }}-client
  labels:
    app: {{ template "socrates.name" . }}-client
    chart: {{ template "socrates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "socrates.name" . }}-client
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "socrates.name" . }}-client
        release: {{ .Release.Name }}
{{- with .Values.client.annotations }}
      annotations:
{{ toYaml . | indent 8 }}       
{{- end }} 
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}    
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.client.resources | indent 12 }}
    {{- with .Values.client.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.client.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.client.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}