apiVersion: v1
kind: Service
metadata:
  name: client
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "socrates.int.explorium.ninja"  
  labels:
    app: {{ template "socrates.name" . }}-client
    chart: {{ template "socrates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "socrates.name" . }}-client
    release: {{ .Release.Name }}
