apiVersion: v1
kind: Service
metadata:
  name: client
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: "socrates.explorium.ninja"  
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:182893536443:certificate/10de7fff-15f4-4c1b-8326-81d3ce500274"
  #   service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01" 
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
  labels:
    app: {{ template "socrates.name" . }}-client
    chart: {{ template "socrates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    # - name: http
    #   port: 80
    #   targetPort: 80
    - name: https
      port: 443
      targetPort: 80      
  selector:
    app: {{ template "socrates.name" . }}-client
    release: {{ .Release.Name }}
