{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: socrates
spec:
  hosts:
    - "socrates.int.explorium.ninja"
  gateways:
  - "socrates-gateway"
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 80
        host: client
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "socrates-gateway"
spec:
  selector:
    istio: internal-ingressgateway # use internal Istio gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "socrates.int.explorium.ninja"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - "socrates.int.explorium.ninja"
{{- end }}