apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: socrates-engine-storage
spec:
  storageClassName: {{ .Values.server.storageClass }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.server.storage }}