apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "socrates.fullname" . }}-worker
  labels:
    app: {{ template "socrates.name" . }}-worker
    chart: {{ template "socrates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "socrates.fullname" . }}-worker
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "socrates.name" . }}-worker
      release: {{ .Release.Name }}
  volumeClaimTemplates:
  - metadata:
      name: docker-graph-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.worker.storageClass | default "gp2" }}
      resources:
        requests:
          storage: {{ .Values.worker.storage }}      
  template:
    metadata:
      labels:
        app: {{ template "socrates.name" . }}-worker
        release: {{ .Release.Name }}
{{- with .Values.worker.annotations }}
      annotations:
{{ toYaml . | indent 8 }}    
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      restartPolicy: Always
      volumes: 
        - name: tmp
          emptyDir: {}
      containers:
        - name: dind-daemon 
          image: docker:dind
          env:    
            - name: DOCKER_HOST 
              value: tcp://localhost:2375
          command: ['dockerd', '-H', 'tcp://0.0.0.0:2375'] 
          securityContext: 
              privileged: true 
          volumeMounts: 
            - name: docker-graph-storage 
              mountPath: /var/lib/docker
            - name: tmp
              mountPath: /tmp    
          ports:
            - name: daemon
              containerPort: 2375
              protocol: TCP                          
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}