apiVersion: v1
kind: Service
metadata:
  name: {{ template "socrates.name" . }}-worker
  labels:
    app: {{ template "socrates.name" . }}-worker
    chart: {{ template "socrates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.worker.service.annotations }}
  annotationss:
{{ toYaml . | indent 4 }}       
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: daemon
      protocol: TCP
      name: daemon
  selector:
    app: {{ template "socrates.name" . }}-worker
    release: {{ .Release.Name }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600