apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: {{ template "socrates.name" . }}-worker
    chart: {{ template "socrates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  # type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: daemon
      protocol: TCP
      name: daemon
  selector:
    app: {{ template "socrates.name" . }}-worker
    release: {{ .Release.Name }}
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 3600

  
