const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Define collection and schema
let FileElement = new Schema({
   isFolder: {
      type: Boolean
   },
   name: {
      type: String
   },
   parent: {
      type: String
   },
   id: { // ID Generated by the UI
      type: String
   },
   type: {
      type: String,
      required: false
   },
   fileid: {
      type: String,
      required: false
   },
   action: {
      type: [String],
      required: false
   }
}, {
   collection: 'files'
})

module.exports = mongoose.model('FileElement', FileElement)